# Generated by Django 3.2.9 on 2021-11-06 16:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
