# Generated by Django 3.2.9 on 2021-11-06 16:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211107_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to=api.models.upload_path, verbose_name='Image'),
        ),
    ]
