# Generated by Django 3.2.9 on 2021-11-06 16:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagedata_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
