# Generated by Django 3.2.9 on 2021-11-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagedata_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
