# Generated by Django 3.2.9 on 2021-11-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211107_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='uploaded_on',
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
