# Generated by Django 3.2.9 on 2021-11-07 01:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211107_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_file',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=api.models.upload_path, width_field='image_width'),
        ),
    ]
