# Generated by Django 3.2.9 on 2021-11-07 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211107_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
