# Generated by Django 3.2.5 on 2021-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211107_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot_Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('X_Coordinate', models.IntegerField()),
                ('Y_Coordinate', models.IntegerField()),
            ],
            options={
                'ordering': ['ids'],
            },
        ),
    ]
