# Generated by Django 3.2.5 on 2021-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plot_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotate_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('classes', models.TextField()),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
