# Generated by Django 3.2.9 on 2021-11-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_temp_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
