# Generated by Django 3.2.9 on 2021-11-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_imagetile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTile',
        ),
    ]
