# Generated by Django 3.2.9 on 2021-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_imagetile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.IntegerField()),
                ('main_image', models.IntegerField()),
            ],
        ),
    ]
