# Generated by Django 3.2.9 on 2021-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_image_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_tile',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image_tile',
            name='main_image',
            field=models.CharField(max_length=1000),
        ),
    ]
