# Generated by Django 3.2.5 on 2021-12-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211127_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField()),
            ],
        ),
    ]
