# Generated by Django 3.2.5 on 2021-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_image_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_coordinate',
            name='Scale',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
