# Generated by Django 3.2.5 on 2022-02-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_plot_coordinate_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_Origin', models.FloatField()),
                ('Y_Origin', models.FloatField()),
                ('Pixel_SizeX', models.FloatField()),
                ('Pixel_SizeY', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='plot_coordinate',
            name='X_Pixel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot_coordinate',
            name='Y_Pixel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
