# Generated by Django 3.2.5 on 2022-02-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220208_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='X_Pixel',
        ),
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='Y_Pixel',
        ),
    ]
