# Generated by Django 3.2.5 on 2022-02-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220208_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot_coordinate',
            old_name='X_Coordinate',
            new_name='X_Pixel',
        ),
        migrations.RenameField(
            model_name='plot_coordinate',
            old_name='Y_Coordinate',
            new_name='Y_Pixel',
        ),
    ]
