# Generated by Django 3.2.5 on 2022-02-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220208_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='Scale',
        ),
    ]
