# Generated by Django 3.2.5 on 2022-02-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_plot_coordinate_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_coordinate',
            name='Scale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
