# Generated by Django 3.2.5 on 2022-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_plot_coordinate_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_coordinate',
            name='X_Coordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot_coordinate',
            name='Y_Coordinate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
