# Generated by Django 3.2.5 on 2022-02-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220208_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='Scale',
        ),
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='X_Pixel',
        ),
        migrations.RemoveField(
            model_name='plot_coordinate',
            name='Y_Pixel',
        ),
        migrations.AlterField(
            model_name='plot_coordinate',
            name='X_Coordinate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plot_coordinate',
            name='Y_Coordinate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temp_data',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temp_data',
            name='lng',
            field=models.FloatField(),
        ),
    ]
