# Generated by Django 3.2.5 on 2022-02-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220212_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot_coordinate',
            name='Scale',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot_coordinate',
            name='X_Pixel',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot_coordinate',
            name='Y_Pixel',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
